### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by delegating** [dmenafro/list-printer-driver-files#1]
I get an error about Param: aram : The term 'Param' is not recognized as the name of a cmdlet.

How do I define the servername and outputpath, is it like so:
$servername = "localhost"
$outputpath = "C:\temp"
As you can see I'm wating to run this script on the computer im on, not a remote server.

I tried moving the param line to the top of the script, but then get loads of werrors as below:
New-Object : The member "Path" was not found for the specified .NET object.
At C:\Users\user\Desktop\To Delete\Untitled1.ps1:8 char:5
+     New-Object PSObject -Property @{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], InvalidOperationException

**Comment by dmenafro** [comment]
Thanks for reaching out!

I found a number of issues with the existing code, and replaced the script with an updated/tested version.

Please let me know if you have any more questions.

Thanks again!

**Comment by dmenafro** [comment]
erroneously closed issue (new to github, sorry). Please close the issue or let me know to do so.
Thanks!

**Comment by delegating** [comment]
Yes, thats got it! Great little script :) Many thanks.
